name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    name: Windows executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --locked
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: clippy-converter-windows
          path: target/release/clippy-converter.exe
